services:
    - type: web
      name: mini-e-commerce-api
      env: node
      region: oregon
      buildCommand: npm install
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 10000
          - key: DB_HOST
            value: shinkansen.proxy.rlwy.net
          - key: DB_NAME
            value: railway
          - key: DB_USER
            value: root
          - key: DB_PASSWORD
            value: MXkiHMUeWkWojCWCEuPdoTtVGszxnxAl
          - key: DB_PORT
            value: 11881
          - key: JWT_SECRET
            generateValue: true
      healthCheckPath: /
